1..15
# Started on 03/22/16 21:58:32
# Starting class: TestAnotherThing
ok     1	TestAnotherThing.test1_Success1
ok     2	TestAnotherThing.test1_Success2
not ok 3	TestAnotherThing.test2_Err1
#   test/test_with_err_fail_pass.lua:41: attempt to perform arithmetic on a table value
not ok 4	TestAnotherThing.test2_Err2
#   test/test_with_err_fail_pass.lua:45: attempt to perform arithmetic on a table value
not ok 5	TestAnotherThing.test3_Fail1
#   test/test_with_err_fail_pass.lua:49: expected: 0, actual: 2
not ok 6	TestAnotherThing.test3_Fail2
#   test/test_with_err_fail_pass.lua:53: expected: 0, actual: 3
# Starting class: TestSomething
ok     7	TestSomething.test1_Success1
ok     8	TestSomething.test1_Success2
not ok 9	TestSomething.test2_Fail1
#   test/test_with_err_fail_pass.lua:15: expected: 0, actual: 2
not ok 10	TestSomething.test2_Fail2
#   test/test_with_err_fail_pass.lua:19: expected: 0, actual: 3
not ok 11	TestSomething.test3_Err1
#   test/test_with_err_fail_pass.lua:23: attempt to perform arithmetic on a table value
not ok 12	TestSomething.test3_Err2
#   test/test_with_err_fail_pass.lua:27: attempt to perform arithmetic on a table value
not ok 13	testFuncErr1
#   test/test_with_err_fail_pass.lua:66: attempt to perform arithmetic on a table value
not ok 14	testFuncFail1
#   test/test_with_err_fail_pass.lua:62: expected: 0, actual: 3
ok     15	testFuncSuccess1
# Ran 15 tests in 0.003 seconds, 5 successes, 5 failures, 5 errors
